# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: ghcr.io/uds-packages/reference-package/container/reference-package
  tag: v0.1.0
  pullPolicy: IfNotPresent
