# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: reference-package-minio-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $accessKey := .Values.minio.accessKey }}
  {{- $secretKey := .Values.minio.secretKey }}
  {{- $secret := "" }}
  {{- if and .Values.minio.existingSecret.name (eq .Values.minio.accessKey "") }}
  {{- $secret = (lookup "v1" "Secret" .Release.Namespace .Values.minio.existingSecret.name) }}
  {{- end }}
  {{- if $secret }}
  {{- $accessKey = index $secret.data .Values.minio.existingSecret.accessKeyKey | b64dec }}
  {{- $secretKey = index $secret.data .Values.minio.existingSecret.secretKeyKey | b64dec }}
  {{- end }}
  S3_ACCESS_KEY: {{ $accessKey | quote }}
  S3_SECRET_KEY: {{ $secretKey | quote }}
{{- end }}
