# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: reference-package
  tag: v0.1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

logging:
  dbLevel: "info" # error, warn, info, debug

database:
  secretName: "reference-package-postgres"
  secretKey: "PASSWORD"

minio:
  enabled: false
  bucket: "reference"
  endpoint: "uds-minio-hl.minio.svc.cluster.local:9000"
  useSSL: false
  # Credentials secret rendered by the uds-reference-package-config chart
  secretName: "reference-package-minio-creds"
  accessKeyKey: "S3_ACCESS_KEY"
  secretKeyKey: "S3_SECRET_KEY"

sso:
  enabled: false
  secretName: reference-package-sso

monitoring:
  enabled: false
