# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: reference-package
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

logging:
  dbLevel: "info" # error, warn, info, debug

database:
  secretName: "reference-package-postgres"
  secretKey: "PASSWORD"

sso:
  enabled: false
  secretName: reference-package-sso

monitoring:
  enabled: false
