# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-package
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-package
  template:
    metadata:
      labels:
        app: reference-package
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: reference-package
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_LOG_LEVEL
              value: {{ .Values.logging.dbLevel | default "info" | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
            - name: MONITORING_ENABLED
              value: {{ .Values.monitoring.enabled | quote }}
          {{- if .Values.sso.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.sso.secretName }}
          {{- end }}
